# Site settings
title: TIY ATX UI Design August 2015
email: abby@theironyard.com
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: "/Curriculum" # the subpath of your site, e.g. /blog/
twitter_username: abbylarner
github_username:  abbylarner

# Build settings
markdown: kramdown
